name: Test and Deploy

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy SSH key
        run: |
          echo "$EC2_SSH_KEY" > key.pem
          chmod 600 key.pem
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy via SSH
        run: |
          ssh -o StrictHostKeyChecking=no -i key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} '
            cd projeto && 
            echo "=== Initial disk usage ===" &&
            sudo df -h &&
            echo "=== Pulling latest code ===" &&
            git pull &&
            echo "=== Stopping containers ===" &&
            sudo docker-compose down && 
            echo "=== Cleaning Docker system ===" &&
            sudo docker container prune -f &&
            sudo docker image prune -af &&
            sudo docker volume prune -f &&
            sudo docker network prune -f &&
            sudo docker system prune -af --volumes &&
            echo "=== Disk usage after cleanup ===" &&
            sudo df -h &&
            echo "=== Building new containers ===" &&
            sudo docker-compose build --no-cache && 
            echo "=== Starting containers ===" &&
            sudo docker-compose up -d &&
            echo "=== Final disk usage ===" &&
            sudo df -h &&
            echo "=== Checking container status ===" &&
            sudo docker-compose ps &&
            echo "=== Deployment completed!!! ==="
          '
